server:
  port: 6898
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck: 
      enabled: true
spring:
  application:
    name: eurekaclient1
  profiles:
    active: dev
